### ISSUE TITLE
is support Android

### ISSUE THREAD

**Issue by yzyspy** [mattboyer/sqbrite#15]

**Comment by mattboyer** [comment]
Sorry @yzyspy , I was away from GitHub for a little while.

I'm not sure I quite understand your question. sqbrite itself should run on any Python 3 environment, although admittedly, I've only tested it on ArchLinux.

If your question refers to the ability to recover deleted records in SQLite databases used by the Android operating system, then the answer is that sqbrite _should_ allow that **provided** someone adds heuristics to the YAML file.

I've moved on to a different project, so I'm not actively working on sqbrite at the moment but I'd be delighted to see pull requests with heuristics for Android SQLite databases.

Hope this helps!
